apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: etcd-backup-operator
    chart: etcd-operator-0.8.3
    heritage: Tiller
    release: etcd-operator
  name: etcd-operator-etcd-operator-etcd-backup-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: etcd-operator
    chart: etcd-operator-0.8.3
    heritage: Tiller
    release: etcd-operator
  name: etcd-operator-etcd-operator-etcd-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: etcd-restore-operator
    chart: etcd-operator-0.8.3
    heritage: Tiller
    release: etcd-operator
  name: etcd-operator-etcd-operator-etcd-restore-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: etcd-operator
    chart: etcd-operator-0.8.3
    heritage: Tiller
    release: etcd-operator
  name: etcd-operator-etcd-operator-etcd-operator
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  - etcdbackups
  - etcdrestores
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: etcd-operator
    chart: etcd-operator-0.8.3
    heritage: Tiller
    release: etcd-operator
  name: etcd-operator-etcd-operator-etcd-backup-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcd-operator-etcd-operator-etcd-operator
subjects:
- kind: ServiceAccount
  name: etcd-operator-etcd-operator-etcd-backup-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: etcd-operator
    chart: etcd-operator-0.8.3
    heritage: Tiller
    release: etcd-operator
  name: etcd-operator-etcd-operator-etcd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcd-operator-etcd-operator-etcd-operator
subjects:
- kind: ServiceAccount
  name: etcd-operator-etcd-operator-etcd-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: etcd-restore-operator
    chart: etcd-operator-0.8.3
    heritage: Tiller
    release: etcd-operator
  name: etcd-operator-etcd-operator-etcd-restore-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcd-operator-etcd-operator-etcd-operator
subjects:
- kind: ServiceAccount
  name: etcd-operator-etcd-operator-etcd-restore-operator
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd-restore-operator
    chart: etcd-operator-0.8.3
    heritage: Tiller
    release: etcd-operator
  name: etcd-restore-operator
spec:
  ports:
  - name: http-etcd-restore-port
    port: 19999
    protocol: TCP
  selector:
    app: etcd-restore-operator
    release: etcd-operator
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: etcd-backup-operator
    chart: etcd-operator-0.8.3
    heritage: Tiller
    release: etcd-operator
  name: etcd-operator-etcd-operator-etcd-backup-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-operator-etcd-operator-etcd-backup-operator
      release: etcd-operator
  template:
    metadata:
      labels:
        app: etcd-operator-etcd-operator-etcd-backup-operator
        release: etcd-operator
      name: etcd-operator-etcd-operator-etcd-backup-operator
    spec:
      containers:
      - command:
        - etcd-backup-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: quay.io/coreos/etcd-operator:v0.9.3
        imagePullPolicy: Always
        name: etcd-backup-operator
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceAccountName: etcd-operator-etcd-operator-etcd-backup-operator
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: etcd-operator
    chart: etcd-operator-0.8.3
    heritage: Tiller
    release: etcd-operator
  name: etcd-operator-etcd-operator-etcd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-operator-etcd-operator-etcd-operator
      release: etcd-operator
  template:
    metadata:
      labels:
        app: etcd-operator-etcd-operator-etcd-operator
        release: etcd-operator
      name: etcd-operator-etcd-operator-etcd-operator
    spec:
      containers:
      - command:
        - etcd-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: quay.io/coreos/etcd-operator:v0.9.3
        imagePullPolicy: Always
        name: etcd-operator-etcd-operator-etcd-operator
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceAccountName: etcd-operator-etcd-operator-etcd-operator
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: etcd-restore-operator
    chart: etcd-operator-0.8.3
    heritage: Tiller
    release: etcd-operator
  name: etcd-operator-etcd-operator-etcd-restore-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-restore-operator
      release: etcd-operator
  template:
    metadata:
      labels:
        app: etcd-restore-operator
        release: etcd-operator
      name: etcd-operator-etcd-operator-etcd-restore-operator
    spec:
      containers:
      - command:
        - etcd-restore-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVICE_ADDR
          value: etcd-restore-operator:19999
        image: quay.io/coreos/etcd-operator:v0.9.3
        imagePullPolicy: Always
        name: etcd-restore-operator
        ports:
        - containerPort: 19999
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceAccountName: etcd-operator-etcd-operator-etcd-restore-operator
