apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations: null
  labels:
    app: kube-state-metrics
    release: prometheus-operator
  name: prometheus-operator-kube-state-metrics
spec:
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  readOnlyRootFilesystem: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - secret
