apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kube-state-metrics
    release: prometheus-operator
  name: psp-prometheus-operator-kube-state-metrics
rules:
- apiGroups:
  - extensions
  resourceNames:
  - prometheus-operator-kube-state-metrics
  resources:
  - podsecuritypolicies
  verbs:
  - use
