apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: kube-state-metrics
    release: prometheus-operator
  name: prometheus-operator-kube-state-metrics
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kube-state-metrics
    release: prometheus-operator
  type: ClusterIP
