apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus-operator-alertmanager
    release: prometheus-operator
  name: prometheus-operator-alertmanager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-alertmanager
subjects:
- kind: ServiceAccount
  name: prometheus-operator-alertmanager
  namespace: default
