apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operator-alertmanager
    release: prometheus-operator
  name: prometheus-operator-alertmanager
spec:
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    alertmanager: prometheus-operator-alertmanager
    app: alertmanager
  type: ClusterIP
