apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: discoveryserver
  labels:
    app: discovery
spec:
  selector:
    matchLabels:
      app: discoveryserver
  endpoints:
  - port: "web"
