apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-operator-operator
    release: prometheus-operator
  name: prometheus-operator-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-operator-operator
      release: prometheus-operator
  template:
    metadata:
      labels:
        app: prometheus-operator-operator
        chart: prometheus-operator-5.0.11
        heritage: Tiller
        release: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/prometheus-operator-kubelet
        - --logtostderr=true
        - --crd-apigroup=monitoring.coreos.com
        - --localhost=127.0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.29.0
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.29.0
        imagePullPolicy: IfNotPresent
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator-operator
