apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus-operator-prometheus
    release: prometheus-operator
  name: prometheus-operator-prometheus-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-prometheus-psp
subjects:
- kind: ServiceAccount
  name: prometheus-operator-prometheus
  namespace: default
