---
# Source: prometheus-operator/templates/prometheus/rolebinding-specificNamespace.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBindingList
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: prometheus-operator-prometheus
    labels:
      app: prometheus-operator-prometheus
      
      chart: prometheus-operator-5.0.11
      release: "prometheus-operator"
      heritage: "Tiller"
    namespace: "kube-system"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-operator-prometheus
  subjects:
  - kind: ServiceAccount
    name: prometheus-operator-prometheus
    namespace: default
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: prometheus-operator-prometheus
    labels:
      app: prometheus-operator-prometheus
      
      chart: prometheus-operator-5.0.11
      release: "prometheus-operator"
      heritage: "Tiller"
    namespace: "default"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-operator-prometheus
  subjects:
  - kind: ServiceAccount
    name: prometheus-operator-prometheus
    namespace: default