apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: prometheus-operator-prometheus
    release: prometheus-operator
  name: prometheus-operator-prometheus-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-operator-prometheus
subjects:
- kind: ServiceAccount
  name: prometheus-operator-prometheus
  namespace: default
