apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: prometheus-operator-prometheus
    release: prometheus-operator
  name: prometheus-operator-prometheus-config
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
