---
# Source: prometheus-operator/templates/prometheus/role-specificNamespace.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleList
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: prometheus-operator-prometheus
    labels:
      app: prometheus-operator-prometheus
      
      chart: prometheus-operator-5.0.11
      release: "prometheus-operator"
      heritage: "Tiller"
    namespace: "kube-system"
  rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: prometheus-operator-prometheus
    labels:
      app: prometheus-operator-prometheus
      
      chart: prometheus-operator-5.0.11
      release: "prometheus-operator"
      heritage: "Tiller"
    namespace: "default"
  rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch