apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operator-prometheus
    release: prometheus-operator
  name: prometheus-operator-prometheus
spec:
  ports:
  - name: web
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus
    prometheus: prometheus-operator-prometheus
  type: ClusterIP
