---
# Source: etcd-operator/templates/backup-operator-clusterrole-binding.yaml

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: etcd-operator-etcd-operator-etcd-backup-operator
  labels:
    chart: "etcd-operator-0.8.3"
    app: etcd-operator
    heritage: Tiller
    release: etcd-operator
subjects:
- kind: ServiceAccount
  name: etcd-operator-etcd-operator-etcd-backup-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcd-operator-etcd-operator-etcd-operator
