---
# Source: etcd-operator/templates/restore-operator-service-account.yaml

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-operator-etcd-operator-etcd-restore-operator
  labels:
    chart: "etcd-operator-0.8.3"
    app: etcd-restore-operator
    heritage: Tiller
    release: etcd-operator