apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-operator-prometheus:9090/
      access: proxy
      isDefault: true
kind: ConfigMap
metadata:
  labels:
    app: prometheus-operator-grafana
    grafana_datasource: "1"
    release: prometheus-operator
  name: prometheus-operator-grafana-datasource
