apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: prometheus-node-exporter
    jobLabel: node-exporter
    release: prometheus-operator
  name: psp-prometheus-operator-prometheus-node-exporter
rules:
- apiGroups:
  - extensions
  resourceNames:
  - prometheus-operator-prometheus-node-exporter
  resources:
  - podsecuritypolicies
  verbs:
  - use
