apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus-node-exporter
    jobLabel: node-exporter
    release: prometheus-operator
  name: psp-prometheus-operator-prometheus-node-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-prometheus-operator-prometheus-node-exporter
subjects:
- kind: ServiceAccount
  name: prometheus-operator-prometheus-node-exporter
  namespace: default
