apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: prometheus-node-exporter
    jobLabel: node-exporter
    release: prometheus-operator
  name: prometheus-operator-prometheus-node-exporter
spec:
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: prometheus-node-exporter
    release: prometheus-operator
  type: ClusterIP
