apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: grafana
    release: prometheus-operator
  name: prometheus-operator-grafana-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-grafana-clusterrole
subjects:
- kind: ServiceAccount
  name: prometheus-operator-grafana
  namespace: default
