apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: grafana
    release: prometheus-operator
  name: prometheus-operator-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      release: prometheus-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
        release: prometheus-operator
    spec:
      containers:
      - env:
        - name: LABEL
          value: grafana_dashboard
        - name: FOLDER
          value: /tmp/dashboards
        image: kiwigrid/k8s-sidecar:0.0.13
        imagePullPolicy: IfNotPresent
        name: grafana-sc-dashboard
        resources: {}
        volumeMounts:
        - mountPath: /tmp/dashboards
          name: sc-dashboard-volume
      - env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: admin-user
              name: prometheus-operator-grafana
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: prometheus-operator-grafana
        image: grafana/grafana:6.0.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          timeoutSeconds: 30
        name: grafana
        ports:
        - containerPort: 80
          name: service
          protocol: TCP
        - containerPort: 3000
          name: grafana
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
        resources: {}
        volumeMounts:
        - mountPath: /etc/grafana/grafana.ini
          name: config
          subPath: grafana.ini
        - mountPath: /etc/grafana/ldap.toml
          name: ldap
          subPath: ldap.toml
        - mountPath: /var/lib/grafana
          name: storage
        - mountPath: /tmp/dashboards
          name: sc-dashboard-volume
        - mountPath: /etc/grafana/provisioning/dashboards/sc-dashboardproviders.yaml
          name: sc-dashboard-provider
          subPath: provider.yaml
        - mountPath: /etc/grafana/provisioning/datasources
          name: sc-datasources-volume
      initContainers:
      - env:
        - name: METHOD
          value: LIST
        - name: LABEL
          value: grafana_datasource
        - name: FOLDER
          value: /etc/grafana/provisioning/datasources
        image: kiwigrid/k8s-sidecar:0.0.13
        imagePullPolicy: IfNotPresent
        name: grafana-sc-datasources
        resources: {}
        volumeMounts:
        - mountPath: /etc/grafana/provisioning/datasources
          name: sc-datasources-volume
      securityContext:
        fsGroup: 472
        runAsUser: 472
      serviceAccountName: prometheus-operator-grafana
      volumes:
      - configMap:
          name: prometheus-operator-grafana
        name: config
      - name: ldap
        secret:
          items:
          - key: ldap-toml
            path: ldap.toml
          secretName: prometheus-operator-grafana
      - emptyDir: {}
        name: storage
      - emptyDir: {}
        name: sc-dashboard-volume
      - configMap:
          name: prometheus-operator-grafana-config-dashboards
        name: sc-dashboard-provider
      - emptyDir: {}
        name: sc-datasources-volume
