apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: grafana
    release: prometheus-operator
  name: prometheus-operator-grafana
rules:
- apiGroups:
  - extensions
  resourceNames:
  - prometheus-operator-grafana
  resources:
  - podsecuritypolicies
  verbs:
  - use
