apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: grafana
    release: prometheus-operator
  name: prometheus-operator-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-operator-grafana
subjects:
- kind: ServiceAccount
  name: prometheus-operator-grafana
  namespace: default
