apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  labels:
    app: webhook
    chart: webhook-v0.7.0
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-webhook-tls
  namespace: cert-manager
spec:
  dnsNames:
  - cert-manager-webhook
  - cert-manager-webhook.cert-manager
  - cert-manager-webhook.cert-manager.svc
  duration: 8760h
  issuerRef:
    name: cert-manager-webhook-ca
  secretName: cert-manager-webhook-webhook-tls
