apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  labels:
    app: webhook
    chart: webhook-v0.7.0
    heritage: Tiller
    release: cert-manager
  name: cert-manager-webhook-selfsign
  namespace: cert-manager
spec:
  selfSigned: {}
