apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator-kube-state-metrics
    chart: prometheus-operator-5.0.11
    heritage: Tiller
    release: prometheus-operator
  name: prometheus-operator-kube-state-metrics
spec:
  endpoints:
  - honorLabels: true
    port: http
  jobLabel: app
  selector:
    matchLabels:
      app: kube-state-metrics
      release: prometheus-operator
